
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoucqgabzyvkibugetwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdWNxZ2Fienl2a2lidWdldHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjM0MjUsImV4cCI6MjA1OTgzOTQyNX0.5yySxthWBRRnR88EJYmIA2jL31RlCFeSi19pRj6Md7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});
